server:
  port: 8762
spring:
  application:
    name: scn-eureka-service
eureka:
  client:
    service-url:
      defaultZone: http://LagouSCEurekaServer1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: LagouSCEurekaServer2