eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${server.version}
    metadata-map:
      key1: value1
      key2: value2
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

server:
  config:
    test: hello, world! - 1314
