server:
  port: 7001
spring:
  application:
    name: scn-gateway
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        - id: autoDeliver-application-router
          # uri: http://127.0.0.1:8091
          uri: lb://autoDeliver-application
          predicates:
            - Path=/autoDeliver/**
        - id: resume-application-router
          # uri: http://127.0.0.1:8081
          uri: lb://resume-application
          predicates:
            - Path=/resume/**
        - id: autoDeliver-application-router-with-filter
          uri: lb://autoDeliver-application
          predicates:
            - Path=/api/autoDeliver/**
          filters:
            - StripPrefix=1
        - id: resume-application-router-with-filter
          uri: lb://resume-application
          predicates:
            - Path=/api/resume/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://LagouSCEurekaServer1:8761/eureka,http://LagouSCEurekaServer2:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
# 开启健康检查接口 /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#分布式链路追踪
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
